### ISSUE TITLE
Problem with assets jsoneditor-icons.png

### ISSUE THREAD

**Issue by must-not-code** [wild-r/activeadmin_hstore_editor#6]
Hi, i have some issue with jsoneditor-icons.png on production.
![404](https://cloud.githubusercontent.com/assets/1628850/5058642/ba6775ac-6d09-11e4-8198-552caa492766.png)
rails 4.1.5
activeadmin 1.0.0.pre (current from gem 'activeadmin', github: 'activeadmin')
activeadmin_hstore_editor 0.0.4
config.assets.precompile += %w(*.png *.jpg *.jpeg *.gif) didn't help

**Comment by misner** [comment]
I got the same bug. I found in your assets the file jsoneditor-icons.png
but it fails to compile it.
When I load the page the icons do not appear and the empty icon, goes to http://exampleapp.com/assets/active_admin/img/jsoneditor-icons.png

But where should I place in my Rails 4 app the file jsoneditor-icons.png ? should I manually compile it in Initializer/asset.rb

I tried putting it in /app/assets/images/active_admin/img/jsoneditor-icons.png. did not work
Tried also /app/assets/active_admin/img/jsoneditor-icons.png, did not work either.

Pls advise.

**Comment by misner** [comment]
For the sake of other people running into the same issue: I figured it out: actually the image jsoneditor-icons.png was being loaded via the gem to to my assets but its location was: https://myapp.com/assets/img/jsoneditor-icons.png

But on active admin, the icons were til empty because, after checking via chrom debug tools, they were pointing to https://myapp.com/assets/active_admin/img/jsoneditor-icons.png instead of https://myapp.com/assets/img/jsoneditor-icons.png

I tried to understand why to no avail.

Hte only solution I found is to override the Gem css and creating the css to the the image hosted on my cdn.

For example
.jsoneditor .field.empty {
  background-image: url("http:/mycdn.active-admin-images/jsoneditor-icons.png") !important;
  background-position: 0 -144px;
}

**Comment by heridev** [comment]
yeah It was failing for me as well, what I did what to download the image and place it in the following folder:
```
app/assets/images/active_admin/img/jsoneditor-icons.png
```
